# Generated by Django 5.0.3 on 2024-03-31 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('status', 'end_date'), 'verbose_name': 'task', 'verbose_name_plural': 'tasks'},
        ),
    ]
