# Generated by Django 5.0.3 on 2024-03-31 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0002_alter_task_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='start_date',
        ),
    ]
